name: Node.js CI

on:
  pull_request:
    branches-ignore:
      - docs
  push:
    branches-ignore:
      - docs

jobs:

  lint:

    name: Lint Files

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18 >=18.1
    - run: |
        npm install
        npm run lint

  test:

    name: Test (Node.js ${{ matrix.node-version }} on ${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['14.0.0', '18']
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - node-version: '14'
          os: ubuntu-latest
        - node-version: '16'
          os: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm install
        npm test

  make-docs:

    name: Generate Documentation

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: |
        npm install
        npm run make-docs -- --no-gitignore
    - uses: actions/upload-artifact@v3
      with:
        name: docs
        path: docs

  publish-docs:

    if: github.ref == 'refs/heads/main'

    name: Publish Documentation

    needs: make-docs

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: docs
        path: docs
    - run: |
        cp _config.yml docs/
        git config --global user.email '<>'
        git config --global user.name 'GitHub Actions Workflow'
        git checkout -b docs
        git add docs
        git commit -m 'Publish documentation'
        git push --force --set-upstream origin docs
